### PR TITLE
wsk property command supports setting and deleting multiple properties

### LINKED ISSUE #889: Go CLI `property set|delete` does not correctly handle multiple properties
## Environment details:

* local deployment, vagrant, native ubuntu (any environment should have this issue)

## Steps to reproduce the issue:
The following command comes from https://new-console.ng.bluemix.net/openwhisk/cli

 `wsk property set --apihost openwhisk.ng.bluemix.net --auth <yourBluemixWhiskAuthKey> --namespace <yourBluemixIdNamespace>`   

## Provide the expected results and outputs:

```
ok: whisk auth set
ok: whisk API host set to 'openwhisk.ng.bluemix.net'
ok: whisk namespace set to '<yourBluemixIdNamespace>'
```

## Provide the actual results and outputs:
There is no indication that the --auth or --apihost values were set.  Depending on whether the current property settings already point to your Bluemix host/auth, you may encounter one of the following failures.
```
error: Authenticated user does not have namespace '<yourBluemixIdNamespace>'
```
or
```
ok: whisk namespace set to '<yourBluemixIdNamespace>'
```

### PR DESCRIPTION
**Pull request by mdeuser**
- Process all auth properties that are specified
- Include `ok` message for each property that is set
- Validate new namespace in context of current property values, including those set via same command
- Fixes #889

### CODE REVIEW

**Comment by rabbah** [comment]
Add tests? WskBasicTests (see line 100).

**Comment by mdeuser** [comment]
@dubeejw - Ready for review

**Comment by mdeuser** [comment]
@rabbah - Added test `set multiple property values with single command` that validates setting auth, apihost, and apiversion all in one command

**Comment by rabbah** [comment]
great - where? it's not pushed to this pr?

**Comment by mdeuser** [comment]
hmm.. file update was lost during attempt to patch that file to pick up changes from another pr.  Re-merged and squashed commits.

**Comment by mdeuser** [comment]
IPG 316

File: tests/src/system/basic/WskBasicTests.scala [hunk 1]
```diff
@@ -107,6 +107,20 @@ class WskBasicTests
         wskprops.delete()
     }
 
+    it should "set multiple property values with single command" in {
```
Comment (dubeejw) [inline tests/src/system/basic/WskBasicTests.scala]: Is there also a test for unsetting multiple properties?

Comment (mdeuser) [inline tests/src/system/basic/WskBasicTests.scala]: Good idea.  I'll one.

**Comment by mdeuser** [comment]
@dubeejw - Test case updated.  Any additional comments?  Thanks!
