### PR TITLE
Reject activation if entity size exceeds limit

### LINKED ISSUE #1059: Short-circuit invokes/fires with a payload being too big
#1044 and the work on #1046 surfaced that the controller is currently not checking the payload size for action invokes or trigger fires. In fact Kafka doesn't take messages bigger than 1MB.

When trying to invoke an action with a bigger payload than 1MB the Kafka Producer throws a `RecordTooLargeException` which is propagated to the user. #1046 fixes the propagation and instead returns the proper HTTP error for it.

We should still implement a short-circuit on the API itself, checking the payload size and returning before even trying to put the message into Kafka.

### PR DESCRIPTION
**Pull request by rabbah**
Action and trigger activations are subject to limits on the content payload. This pull request enforces the limit earlier in the pipeline.

PG2//971 approved.
Fixes #1059.

### CODE REVIEW

File: common/scala/src/main/scala/whisk/core/entity/ActivationEntityLimit.scala [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+import whisk.core.entity.size.SizeInt
+
+/**
+ * ActivationEntityLimit defines the limits on the input/output payloads for actions
+ * and triggers.
+ */
+
+protected[core] object ActivationEntityLimit {
+    protected[core] val MAX_ACTIVATION_ENTITY_LIMIT = 1.MB
```
Comment (markusthoemmes) [inline common/scala/src/main/scala/whisk/core/entity/ActivationEntityLimit.scala]: Shall we add a comment to clarify that this also correlates with parameters in Kafka?

File: core/controller/src/main/scala/whisk/core/controller/Entities.scala [hunk 2]
```diff
@@ -60,13 +55,15 @@ trait WhiskCollectionAPI
...
     with AuthorizedRouteProvider
-    with ValidateEntitySize
+    with ValidateRequestSize
     with ReadOps
     with WriteOps {
 
     /** The core collections require backend services to be injected in this trait. */
     services: WhiskServices =>
 
+    protected val allowedActivationEntitySize: Long = ActivationEntityLimit.MAX_ACTIVATION_ENTITY_LIMIT.toBytes
```
Comment (markusthoemmes) [inline core/controller/src/main/scala/whisk/core/controller/Entities.scala]: Keep it as `ByteSize` here and use `toBytes` where necessary?

File: common/scala/src/main/scala/whisk/core/entity/WhiskEntity.scala [hunk 3]
```diff
@@ -158,9 +156,16 @@ case class LimitedWhiskEntityPut(
...
+        exec.flatMap { e =>
+            val is = e.size
+            if (is <= Exec.sizeLimit) None else Some(is, Exec.sizeLimit)
+        } orElse parameters.flatMap { p =>
+            val is = p.size
+            if (is <= Parameters.sizeLimit) None else Some(is, Parameters.sizeLimit)
+        } orElse annotations.flatMap { a =>
+            val is = a.size
+            if (is <= Parameters.sizeLimit) None else Some(is, Parameters.sizeLimit)
+        }
```
Comment (markusthoemmes) [inline common/scala/src/main/scala/whisk/core/entity/WhiskEntity.scala]: The return value of this could be confusing with regards to the error message returned to the user. If I paste a 40MB file and 2MB parameters I will get: Something like: You sent 2Megabytes but only 1 is allowed. Maybe we should add the `field` as well and put that into the error message?

File: core/controller/src/main/scala/whisk/core/controller/Entities.scala (hunk 2 above)
Comment (rabbah) [inline core/controller/src/main/scala/whisk/core/controller/Entities.scala]: We have to do this conversion on every API call. I don't think it's worth it.

File: common/scala/src/main/scala/whisk/core/entity/ActivationEntityLimit.scala (hunk 1 above)
Comment (rabbah) [inline common/scala/src/main/scala/whisk/core/entity/ActivationEntityLimit.scala]: Not yet.

File: common/scala/src/main/scala/whisk/core/entity/WhiskEntity.scala (hunk 3 above)
Comment (rabbah) [inline common/scala/src/main/scala/whisk/core/entity/WhiskEntity.scala]: https://github.com/openwhisk/openwhisk/pull/1779/commits/eb5e6112d46887aed7732d64d4e284b90df9bf82.

**Comment by rabbah** [comment]
Addressed feedback from @markusthoemmes. Thank you!

**Comment by rabbah** [comment]
PG2/986 re-approved.
