### PR TITLE
Remove use of go-prettyjson package

### LINKED ISSUE #1142: go cli corrupts activation response
## Environment details:

* all, must use go-cli to reproduce

## Steps to reproduce the issue:

1.   create new action `t`
```
> cat t.js 
function main() {
  return { 'msg': "%" };
}
> wsk action update t t.js
```
2.   invoke blocking using go-cli `bin/go-cli/wsk --apihost 192.168.99.100 -i action invoke -b -r t`
3.   observe corrupted result

## Provide the expected results and outputs:

```
# using python CLI
> wsk --apihost 192.168.99.100 -i action invoke -b -r t
{
    "msg": "%"
}
```

## Provide the actual results and outputs:

```
> bin/go-cli/wsk --apihost 192.168.99.100 -i action invoke -b -r t
{
  "msg": "%!!(MISSING)"(MISSING)
}
```

Without digging too deeply, the go cli attempts to be trying to validate the HTTP response as JSON and that is tripped up by `%` in the response. 

```
> grep -r "(MISSING)" .
Binary file ./bin/go-cli/linux/386/wsk matches
Binary file ./bin/go-cli/linux/amd64/wsk matches
Binary file ./bin/go-cli/linux/arm/wsk matches
Binary file ./bin/go-cli/linux/arm64/wsk matches
Binary file ./bin/go-cli/linux/mips64/wsk matches
Binary file ./bin/go-cli/linux/mips64le/wsk matches
Binary file ./bin/go-cli/linux/ppc64/wsk matches
Binary file ./bin/go-cli/linux/ppc64le/wsk matches
Binary file ./bin/go-cli/mac/386/wsk matches
Binary file ./bin/go-cli/mac/amd64/wsk matches
Binary file ./bin/go-cli/mac/arm/wsk matches
Binary file ./bin/go-cli/mac/arm64/wsk matches
Binary file ./bin/go-cli/windows/386/wsk.exe matches
Binary file ./bin/go-cli/windows/amd64/wsk.exe matches
Binary file ./bin/go-cli/wsk matches
```

This was distilled from observed failures running watson weather tests.

### PR DESCRIPTION
**Pull request by mdeuser**
Remove use of go-prettyjson package due to package issue.
Fixes #1142

### CODE REVIEW

**Comment by mdeuser** [comment]
@dubeejw - ready for review.

**Comment by mdeuser** [comment]
@dubeejw - Ready for merge!

File: tools/go-cli/go-whisk-cli/commands/util.go [hunk 1]
```diff
@@ -506,29 +508,23 @@ func unpackGzip(inpath string, outpath string) error {
     // Make sure the target file does not exist
     if _, err := os.Stat(outpath); err == nil {
         whisk.Debug(whisk.DbgError, "os.Stat reports file '%s' exists\n", outpath)
-        errStr := fmt.Sprintf(
-            wski18n.T("The file {{.name}} already exists.  Delete it and retry.",
-                map[string]interface{}{"name": outpath}))
+        errStr := fmt.Sprintf("The file %s already exists.  Delete it and retry.", outpath)
```
Comment (dubeejw) [inline tools/go-cli/go-whisk-cli/commands/util.go]: @mdeuser, looks like all the externalization of strings in this file got replaced?
